name: objection_handling_test
on: 
  pull_request:
    types: [opened, reopened]
jobs:
  run:
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: iterative/setup-cml@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: cml for Objection Handling
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          sudo pip3 install -r requirements.txt
          sudo python test.py

          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md

          cml-send-comment report.md
        
          git config --local user.email "bandi.s@outplayhq.com"
          git config --local user.name "Bandi Saideva"

          git add metrics.txt
          git commit --message "Added metrics.txt"
          git push origin dummy
        

